apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-filetransfer
  labels:
    app.kubernetes.io/name: filetransfer
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: filetransfer
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: filetransfer
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: filetransfer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu | quote }}
              memory: {{ .Values.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.resources.limits.cpu | quote }}
              memory: {{ .Values.resources.limits.memory | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
          env:
            - name: SERVER_PORT
              value: {{ .Values.env.serverPort | quote }}
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.env.springProfilesActive | quote }}
            - name: AWS_REGION
              value: {{ .Values.env.awsRegion | quote }}
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: AWS_ACCESS_KEY_ID
                  optional: true
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: AWS_SECRET_ACCESS_KEY
                  optional: true
            - name: APP_CREDENTIALS_AZURE_STORAGE_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: APP_CREDENTIALS_AZURE_STORAGE_ACCOUNT_KEY
                  optional: true
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: SPRING_DATASOURCE_URL
                  optional: true
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: SPRING_DATASOURCE_USERNAME
                  optional: true
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: SPRING_DATASOURCE_PASSWORD
                  optional: true
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
                  optional: true
            - name: AZURE_EVENTHUB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: AZURE_EVENTHUB_CONNECTION_STRING
                  optional: true
            - name: AZURE_EVENTHUB_ENABLED
              value: {{ .Values.env.eventHubEnabled | default "false" | quote }}
            - name: AZURE_EVENTHUB_EVENT_HUB_NAME
              value: {{ .Values.env.eventHubName | default "file-transfers" | quote }}
