apiVersion: v1
kind: ConfigMap
metadata:
  name: filetransfer-config
data:
  SERVER_PORT: "8586"
  AWS_REGION: "us-east-1"
  AWS_SECRETS_SECRET_NAME: "s3-to-azure/credentials"
  STORAGE_SOURCE: "s3Service"
  STORAGE_DESTINATION: "azureBlobService"