apiVersion: v1
kind: Secret
metadata:
  name: filetransfer-secret
type: Opaque
stringData:
  MYSQL_USERNAME: "admin"
  MYSQL_PASSWORD: "StrongPassword123"
  MYSQL_URL: "jdbc:mysql://<RDS_ENDPOINT>:3306/filetransfer?createDatabaseIfNotExist=true&useSSL=true&serverTimezone=UTC&allowPublicKeyRetrieval=true"
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  S3_BUCKET_NAME: "aileen-bucket"
  S3_REGION: "us-east-1"
  AZURE_STORAGE_ACCOUNT_NAME: "s3azureconnector123"
  AZURE_STORAGE_ACCOUNT_KEY: "YOUR_AZURE_KEY"
  AZURE_CONTAINER_NAME: "s3-azure-connector"